#!/usr/bin/env bash
# ============================================================
# Name      : network_optimizer.sh
# Version   : 1.0.0
# Author    : Anamicca23
# Tested    : Ubuntu 22.04 LTS, Debian 12 Bookworm
# Min OS    : Ubuntu 20.04 / Debian 11
# Risk      : HIGH
# Sudo      : Required
# Reversible: Yes  (Option [7] restores original resolv.conf)
# Desc      : Flushes systemd-resolved DNS, restarts active
#             interface, sets Google/Cloudflare in resolv.conf
#             (backup saved first), runs latency test.
#             Full undo/restore option included.
# ============================================================

set -uo pipefail

RED='\033[0;31m';  YELLOW='\033[1;33m'; GREEN='\033[0;32m'
CYAN='\033[0;36m'; BOLD='\033[1m';      NC='\033[0m'
DASH="────────────────────────────────────────────────────────"

RESOLV_CONF="/etc/resolv.conf"
RESOLV_BAK="/etc/resolv.conf.netopt_bak"

if [[ $EUID -ne 0 ]]; then
    echo -e "\n  ${RED}[ERROR]${NC} Must be run as root: ${BOLD}sudo ./network_optimizer.sh${NC}\n"
    exit 1
fi

get_active_iface() {
    ip route 2>/dev/null | grep "^default" | awk '{print $5}' | head -1
}

show_menu() {
    local iface; iface=$(get_active_iface)
    clear
    echo -e "${BOLD}${CYAN}"
    echo "  ╔══════════════════════════════════════════════════════╗"
    echo "  ║      LINUX NETWORK OPTIMIZER  v1.0.0                 ║"
    echo "  ║     DNS · Interface Reset · Fast DNS · Latency       ║"
    echo "  ╚══════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo -e "  Active interface: ${BOLD}${iface:-none detected}${NC}"
    echo
    echo -e "  ${BOLD}[1]${NC}  Full Optimization  (flush DNS + set fast DNS)"
    echo -e "  ${BOLD}[2]${NC}  Flush DNS Cache"
    echo -e "  ${BOLD}[3]${NC}  Restart Network Interface"
    echo -e "  ${BOLD}[4]${NC}  Set Fast DNS  (Cloudflare 1.1.1.1 + Google 8.8.8.8)"
    echo -e "  ${BOLD}[5]${NC}  Run Ping Latency Test"
    echo -e "  ${BOLD}[6]${NC}  Show Current Network Info"
    echo -e "  ${BOLD}[7]${NC}  UNDO — Restore Original resolv.conf"
    echo -e "  ${BOLD}[0]${NC}  Exit"
    echo
    printf "  Enter Option: "
    read -r choice
}

flush_dns() {
    echo -e "  Flushing DNS cache..."
    if command -v resolvectl &>/dev/null; then
        resolvectl flush-caches 2>/dev/null && \
            echo -e "  ${GREEN}[OK]${NC} resolvectl cache flushed." || true
    fi
    if systemctl is-active systemd-resolved &>/dev/null; then
        systemctl restart systemd-resolved 2>/dev/null && \
            echo -e "  ${GREEN}[OK]${NC} systemd-resolved restarted." || true
    fi
    # Legacy fallback
    if [[ -x /etc/init.d/dns-clean ]]; then
        /etc/init.d/dns-clean start 2>/dev/null && \
            echo -e "  ${GREEN}[OK]${NC} dns-clean ran." || true
    fi
    if command -v nscd &>/dev/null; then
        nscd -K 2>/dev/null; nscd 2>/dev/null || true
        echo -e "  ${GREEN}[OK]${NC} nscd restarted."
    fi
}

restart_iface() {
    local iface; iface=$(get_active_iface)
    if [[ -z "$iface" ]]; then
        echo -e "  ${YELLOW}[WARN]${NC} No active interface detected."
        return
    fi
    echo -e "  Restarting interface: ${BOLD}${iface}${NC}"
    ip link set "$iface" down 2>/dev/null
    sleep 2
    ip link set "$iface" up   2>/dev/null
    sleep 2
    # Try DHCP renew
    if command -v dhclient &>/dev/null; then
        dhclient "$iface" 2>/dev/null && \
            echo -e "  ${GREEN}[OK]${NC} DHCP renewed on $iface." || true
    elif command -v dhcpcd &>/dev/null; then
        dhcpcd -k "$iface" 2>/dev/null; dhcpcd "$iface" 2>/dev/null || true
    fi
    echo -e "  ${GREEN}[OK]${NC} Interface $iface restarted."
}

set_fast_dns() {
    # Backup resolv.conf first
    if [[ ! -f "$RESOLV_BAK" ]]; then
        cp "$RESOLV_CONF" "$RESOLV_BAK" 2>/dev/null
        echo -e "  ${CYAN}[INFO]${NC} Backup saved: $RESOLV_BAK"
    fi

    # Check if resolv.conf is managed by systemd-resolved
    if [[ -L "$RESOLV_CONF" ]]; then
        echo -e "  ${CYAN}[INFO]${NC} /etc/resolv.conf is a symlink (managed by systemd-resolved)."
        echo -e "  Setting DNS via resolvectl..."
        local iface; iface=$(get_active_iface)
        if [[ -n "$iface" ]]; then
            resolvectl dns "$iface" 1.1.1.1 8.8.8.8 1.0.0.1 8.8.4.4 2>/dev/null && \
                echo -e "  ${GREEN}[OK]${NC} DNS set on $iface via resolvectl." || \
                echo -e "  ${YELLOW}[WARN]${NC} resolvectl DNS set failed. Try NetworkManager."
        fi
    else
        cat > "$RESOLV_CONF" << 'DNS'
# Generated by network_optimizer.sh
# Restore original: /etc/resolv.conf.netopt_bak
nameserver 1.1.1.1
nameserver 8.8.8.8
nameserver 1.0.0.1
nameserver 8.8.4.4
DNS
        echo -e "  ${GREEN}[OK]${NC} resolv.conf updated with Cloudflare + Google DNS."
    fi
}

restore_dns() {
    if [[ -f "$RESOLV_BAK" ]]; then
        cp "$RESOLV_BAK" "$RESOLV_CONF"
        echo -e "  ${GREEN}[OK]${NC} resolv.conf restored from backup."
        flush_dns
    else
        echo -e "  ${YELLOW}[INFO]${NC} No backup found at $RESOLV_BAK"
        echo -e "  Nothing to restore."
    fi
}

ping_test() {
    clear
    echo -e "${BOLD}${CYAN}  PING LATENCY TEST${NC}"
    echo -e "  ${DASH}\n"
    for target in "1.1.1.1 Cloudflare" "8.8.8.8 Google" "9.9.9.9 Quad9" "208.67.222.222 OpenDNS"; do
        local ip;  ip=$(echo  "$target" | awk '{print $1}')
        local lbl; lbl=$(echo "$target" | awk '{print $2}')
        printf "  %-20s " "${lbl} (${ip})"
        local result; result=$(ping -c 4 -q "$ip" 2>/dev/null | \
            grep "rtt\|round-trip" | awk -F'/' '{printf "avg: %.1f ms", $5}' || echo "TIMEOUT")
        echo "$result"
    done
    echo
    echo -e "  Guide: <20ms Excellent  20-50ms Good  50-100ms OK  >100ms Poor"
    echo
}

net_info() {
    clear
    echo -e "${BOLD}${CYAN}  CURRENT NETWORK INFO${NC}"
    echo -e "  ${DASH}\n"
    echo -e "  ${BOLD}Interfaces:${NC}"
    ip -br addr show 2>/dev/null | sed 's/^/  /'
    echo
    echo -e "  ${BOLD}Routes:${NC}"
    ip route 2>/dev/null | sed 's/^/  /'
    echo
    echo -e "  ${BOLD}DNS Servers:${NC}"
    cat /etc/resolv.conf 2>/dev/null | grep "nameserver" | sed 's/^/  /'
    command -v resolvectl &>/dev/null && \
        resolvectl status 2>/dev/null | grep -A3 "DNS Servers" | head -8 | sed 's/^/  /' || true
    echo
    echo -e "  ${BOLD}External IP:${NC}"
    curl -s --max-time 5 https://api.ipify.org 2>/dev/null | sed 's/^/  /' && echo || echo "  N/A"
    echo
}

full_optimize() {
    clear
    echo -e "${BOLD}${CYAN}  RUNNING FULL NETWORK OPTIMIZATION${NC}\n"
    echo -e "  ${BOLD}Before — ping test:${NC}"
    ping -c 3 -q 8.8.8.8 2>/dev/null | grep "rtt\|packet" | sed 's/^/  /' || echo "  (no response)"
    echo
    echo -e "  ${BOLD}[1/3]${NC} Flushing DNS cache..."
    flush_dns
    echo -e "\n  ${BOLD}[2/3]${NC} Setting fast DNS servers..."
    set_fast_dns
    echo -e "\n  ${BOLD}[3/3]${NC} Re-flushing DNS after update..."
    flush_dns
    echo
    echo -e "  ${BOLD}After — ping test:${NC}"
    ping -c 3 -q 8.8.8.8 2>/dev/null | grep "rtt\|packet" | sed 's/^/  /' || echo "  (no response)"
    echo
    echo -e "${GREEN}  [DONE]${NC} Optimization complete. Use option [7] to restore original DNS."
    echo
}

while true; do
    show_menu
    case "$choice" in
        1) full_optimize;   read -rp "  Press Enter..." ;;
        2) flush_dns;  echo; read -rp "  Press Enter..." ;;
        3) restart_iface; echo; read -rp "  Press Enter..." ;;
        4) set_fast_dns;  echo; read -rp "  Press Enter..." ;;
        5) ping_test;          read -rp "  Press Enter..." ;;
        6) net_info;           read -rp "  Press Enter..." ;;
        7) restore_dns; echo;  read -rp "  Press Enter..." ;;
        0) echo -e "\n  Goodbye!\n"; exit 0 ;;
        *) echo -e "  ${RED}Invalid option.${NC}"; sleep 1 ;;
    esac
done
